kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: python
  commands:
    - pip install -r requirements.txt
    - pip install flake8 pytest pytest-async bandit
    - flake8
    - pytest
    - bandit -r n2yo

- name: upload
  image: python
  environment:
    pypi_username:
      from_secret: username
    pypi_password:
      from_secret: password
  commands:
    - pip install --user --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload -u $USERNAME -p $PASSWORD --repository testpypi dist/*
