kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: python
  commands:
    - pip install -r requirements.txt
    - pip install flake8 pytest pytest-asyncio bandit
    - flake8
    - pytest
    - bandit -r n2yo

- name: upload
  image: plugins/pypi
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
